name: 'Update schedule'

on:
  schedule:
    - cron: '0 4,16 * * *'
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  push:
    runs-on: ubuntu-latest
    timeout-minutes: 240
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'
          cache: 'pipenv'

      - name: Install pipenv
        run: pip install --user pipenv

      - name: Install dependencies
        run: |
          pipenv install --deploy --python 3.13

      - name: Update EPG
        run: pipenv run epg

      - name: Commit and push if changed
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add -f output/epg.xml output/epg.gz || true
          if ! git diff --staged --quiet; then
            git commit -m "Github Action Auto Updated"
            git pull --rebase
            git push
          fi
